version: '2'

services:
  pwn1:
    networks:
            - default
    build:
            context: ./pwn1
    pids_limit: 300
    stdin_open: true
    tty: true
    ports:
            - "9999:9999"
    restart: always
  pwn2:
    networks:
            - default
    build:
            context: ./pwn2
    pids_limit: 300
    stdin_open: true
    tty: true
    ports:
            - "4322:4322"
    restart: always
  pwn3:
    networks:
            - default
    build:
            context: ./pwn2
    pids_limit: 300
    stdin_open: true
    tty: true
    ports:
            - "4355:4322"
    restart: always

  # Contest Questions end
